{{- if and .Values.configMap.create .Values.configMap.data }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-frontend.appConfigName" . }}
  namespace: {{ include "todo-frontend.namespace" . }}
  labels:
    {{- include "todo-frontend.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.configMap.data }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
