{{- if .Values.configMap.data }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-backend.configName" . }}
  namespace: {{ include "todo-backend.namespace" . }}
  labels:
    {{- include "todo-backend.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.configMap.data }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
