{{- if and .Values.secret.create .Values.secret.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-backend.secretName" . }}
  namespace: {{ include "todo-backend.namespace" . }}
  labels:
    {{- include "todo-backend.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  {{- range $key, $val := .Values.secret.data }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
