# Environment overrides for prod
namespace:
  name: loginapp-prod
  labels:
    project: loginapp
    environment: prod

image:
  tag: "stable"

replicaCount: 3

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

labels:
  project: loginapp
  environment: prod
